name: validate_it
description: A clean and reusable Flutter package for validating form fields.
version: 0.0.1
homepage: https://github.com/yourusername/validate_it
repository: https://github.com/yourusername/validate_it
issue_tracker: https://github.com/yourusername/validate_it/issues
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
